/// Per-flavor Firebase project credentials (Ch13 / P13).
///
/// ---------------------------------------------------------------------------
/// THIS FILE IS NOT YET POPULATED, AND THAT IS A DELIBERATE, VISIBLE STATE
///
/// Three separate Firebase projects back the three flavors (CLAUDE.md →
/// Flavors). Their credentials are generated by `flutterfire configure`,
/// which needs an interactive Firebase login and the projects to actually
/// exist — neither of which a build agent can do. So [forFlavor] returns
/// `null` for every flavor until a human runs the three commands in
/// `docs/firebase-setup.md`, and the app is written to run correctly in the
/// meantime.
///
/// WHY NULL RATHER THAN PLACEHOLDER CREDENTIALS. Fake-but-well-formed api
/// keys would compile, initialise, and then fail at the first network call
/// with an authentication error that looks like a bug in the app rather than
/// a missing setup step. Worse, they could be shipped. A null is
/// unambiguous, is checked in exactly one place (`bootstrap.dart` step 2),
/// and puts the app into the SAME local-only mode it already has to support
/// for a player in airplane mode — a mode that is tested
/// (`bootstrap_offline_test.dart`) rather than merely hoped for.
///
/// So "unconfigured" and "offline" are one code path, not two. That is worth
/// more than a stub that pretends: it means the degraded path is exercised
/// every time anyone runs the app locally, instead of being discovered by the
/// first player on a train.
///
/// ---------------------------------------------------------------------------
/// HOW TO POPULATE IT
///
/// See `docs/firebase-setup.md` for the full runbook. The short version, once
/// per flavor:
///
/// ```sh
/// dart pub global activate flutterfire_cli
/// flutterfire configure \
///   --project=wsm-dev \
///   --out=lib/app/config/firebase_options_dev.dart \
///   --android-package-name=com.wordsearchmaster.app.dev
/// ```
///
/// Then import each generated file here and return its
/// `DefaultFirebaseOptions.currentPlatform` from the matching switch arm
/// below. The generated files are the ONLY thing that changes; nothing else
/// in the app reads credentials.
library;

import 'package:firebase_core/firebase_core.dart';

import 'app_config.dart';

/// Resolves the Firebase project for a flavor.
abstract final class FlavorFirebaseOptions {
  /// The credentials for [flavor], or null while this file is unpopulated.
  ///
  /// A null return is a supported state, not an error — see the library
  /// header. `bootstrap.dart` skips `Firebase.initializeApp` entirely and
  /// every Firebase-backed service keeps its Noop binding, which leaves a
  /// fully playable offline game.
  static FirebaseOptions? forFlavor(Flavor flavor) => switch (flavor) {
    // TODO(setup): return DevFirebaseOptions.currentPlatform once
    // `flutterfire configure --project=wsm-dev` has been run.
    Flavor.dev => null,
    // TODO(setup): return StgFirebaseOptions.currentPlatform once
    // `flutterfire configure --project=wsm-stg` has been run.
    Flavor.stg => null,
    // TODO(setup): return ProdFirebaseOptions.currentPlatform once
    // `flutterfire configure --project=wsm-prod` has been run.
    Flavor.prod => null,
  };

  /// Whether [flavor] has real credentials.
  ///
  /// Exists so the dev-flavor UI and the tests can SAY which mode the app is
  /// in rather than inferring it from a silent absence of cloud data — a
  /// developer who does not know Firebase is unconfigured will file the
  /// resulting "sync does nothing" as a bug.
  static bool isConfigured(Flavor flavor) => forFlavor(flavor) != null;

  /// The OAuth 2.0 **web** client id for [flavor]'s project, needed by
  /// Google Sign-In on Android so the id token it returns is minted for this
  /// Firebase project rather than for the app's own Android client.
  ///
  /// Copied from that project's `google-services.json`
  /// (`oauth_client` → the entry with `client_type: 3`), NOT from the Android
  /// client id — using the Android one is the single most common cause of
  /// `linkWithCredential` failing with an audience mismatch that reads like a
  /// generic sign-in error.
  static String? googleServerClientId(Flavor flavor) => switch (flavor) {
    // TODO(setup): paste each project's client_type 3 OAuth client id.
    Flavor.dev || Flavor.stg || Flavor.prod => null,
  };
}
